# 使用基础镜像
FROM samge/ms-swift-train-base

# 设置工作目录
WORKDIR /app

# 将项目的文件复制到工作目录中
# COPY . .

# 设置代理环境变量
ARG PROXY
ENV http_proxy=${PROXY} https_proxy=${PROXY}

# 配置启动时执行的脚本，用于设置别名等环境配置
RUN echo "alias pxyon='export https_proxy=${PROXY} http_proxy=${PROXY}'" >> /root/.bashrc && \
    echo "alias pxyoff='unset https_proxy http_proxy'" >> /root/.bashrc && \
    echo "alias giton='git config --global http.proxy \"${PROXY}\" && git config --global https.proxy \"${PROXY}\"'" >> /root/.bashrc && \
    echo "alias gitoff='git config --global --unset http.proxy && git config --global --unset https.proxy'" >> /root/.bashrc

# set PYTHONPATH
RUN echo "export PYTHONPATH=/app" >> ~/.bashrc
ENV PYTHONPATH=/app

# 移除windows下wsl不支持的so文件
# 使用 rm 的 -f 标志避免错误
RUN rm -f /usr/lib/x86_64-linux-gnu/libnvidia-ml*
RUN rm -f /usr/lib/x86_64-linux-gnu/libcuda.so*
RUN rm -f /usr/lib/x86_64-linux-gnu/libcudadebugger.so*

# declare the port on which the container listens
EXPOSE 7860

VOLUME [ "/app", "/root/.cache" ]

# 重置代理配置
ENV http_proxy= https_proxy=